# Generated by Django 5.0.3 on 2024-03-29 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя автора')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия автора')),
                ('date_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('about', models.TextField(verbose_name='Об авторе')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Жанр книги')),
                ('status', models.CharField(choices=[('detective', 'Detective'), ('action and adventure', 'Action and adventure'), ('fantasy', 'Fantasy'), ('roman', 'Roman')], default='roman', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Язык книги')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Издательство')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('product_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='libraryApp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('author', models.ManyToManyField(to='libraryApp.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.genre')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.language')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='BookPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('product_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='libraryApp.book')),
            ],
        ),
    ]
